Fix bug in Chrome Endure tests that prevent WebPageReplay from working.
A bug was introduced in the Chrome Endure tests in
https://chromiumcodereview.appspot.com/11740020
that used an undefined reference to "self" in the event that we're trying
to run endurance tests under WebPageReplay.  This CL fixes that problem.

BUG=None
TEST=Verified that one of the WebPageReplay endurance tests now starts to
run successfully with this change.
NOTRY=True


Review URL: https://chromiumcodereview.appspot.com/12051051

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@178604 0039d316-1c4b-4281-b951-d872f2087c98