Revert r196939 "Add Widevine CDM component installer."
> Add Widevine CDM component installer.
>
> This CL adds a component installer for Widevine CDM on Windows and Mac. Note that it uses a fake extension ID which will be replaced when we have the real one. Also the component is not registered in chrome_browser_main.cc yet. We need to have the real CDMs uploaded to the server to fully test and enable this feature.
>
> BUG=180260
> TEST=Tested local operations (registering plugin, remove old versions, etc) on Linux without sandbox. Will need to test against the server later

Reason: Broke chrome linux build
http://build.chromium.org/p/chromium.chrome/builders/Google%20Chrome%20Linux/builds/29780

  LINK(target) out/Release/test_shell: Finished
  LINK(target) out/Release/content_unittests: Finished
out/Release/obj.target/chrome/../common_constants/chrome/common/chrome_paths.o: In function `.L43':
/b/build/slave/google-chrome-rel-linux/build/src/chrome/common/chrome_paths.cc:363: undefined reference to `kWidevineCdmBaseDirectory'
collect2: ld returned 1 exit status
make: *** [out/Release/remoting_unittests] Error 1
  LINK(target) out/Release/content_shell: Finished
  TOUCH out/Release/obj.target/content/content_shell_builder.stamp

TBR=xhwang@chromium.org
BUG=180260

Review URL: https://codereview.chromium.org/14417012

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@196973 0039d316-1c4b-4281-b951-d872f2087c98