Speculative revert 192366 "NaCl: Update revision in DEPS, r11083 -> r11118"
It looks like this DEPS roll broke NACL on win_x64_rel bot: http://build.chromium.org/p/tryserver.chromium/builders/win_x64_rel/builds/6688

Updating projects from gyp files...
gyp: Dependency 'E:\b\build\slave\win\build\src\native_client\src\shared\platform\platform.gyp:platform64#target' not found while trying to load target E:\b\build\slave\win\build\src\native_client\src\trusted\validator\validator.gyp:validation_cache64#target
Error: Command E:\b\depot_tools\python_bin\python.exe src/build/gyp_chromium returned non-zero exit status 1 in E:\b\build\slave\win\build


> NaCl: Update revision in DEPS, r11083 -> r11118
> 
> This pulls in the following Native Client changes:
> 
> r11084: (shcherbina) Validator_ragel: disable CRC32 <16-bit operand>, <32-bit operand>.
> r11085: (shcherbina) Validator_ragel: extract action bodies and error action from XML.
> r11086: (jvoung) Roll pnacl tools rev to 11078 to pull in the pnacl-finalize script.
> r11087: (mseaborn) PNaCl: Update LLVM revision in pnacl/DEPS
> r11088: (kschimpf) Add ability to run ARM validation multiple times for performance testing.
> r11089: (dschuff) Update pnacl perf_expectations
> r11090: (jvoung) Add a scons pnacl finalize step for pnacl_generate_pexe tests.
> r11091: (kschimpf) Add ability to introduce implicit methods in the ARMv7 validator.
> r11092: (mseaborn) Harden Windows exception handler: Allow resuming from int3 breakpoint only once
> r11093: (jfb) Update PNaCl DEPS to pull in my Cortex-A9 change.
> r11094: (jfb) Update TOOL_REVISIONS, pull in Derek's 'PNaCl ABI: Enable resolve-aliases and nacl-global-cleanup passes'.
> r11095: (shcherbina) Remove vdiff dependency on RDFA decoder.
> r11096: (shcherbina) Validator_ragel: remove autogenerated decoder files from source control.
> r11097: (jfb) Disable assertions in the release sandboxed llc.nexe.
> r11098: (bsy) Add descriptor attributes so metadata about file identity (or other uses) can be plumbed through
> r11099: (jfb) Update perf expectations
> r11100: (mseaborn) PNaCl: Enable the ExpandVarArgs pass for ABI simplification (second try)
> r11101: (jfb) Update TOOL_REVISIONS for PNaCl.
> r11102: (jvoung) Update PNaCl DEPS to start building the -strip-metadata pass.
> r11103: (mseaborn) Harden Windows exception handler: Check NaClAppThread's suspend_state
> r11104: (jfb) Update TOOL_REVISIONS.
> r11105: (shcherbina) Validator_ragel: disallow multiple legacy prefixes in 32-bit mode for compatibility with old validator.
> r11106: (shcherbina) Validator_ragel: custom code generator.
> r11107: (mseaborn) PNaCl: Update LLVM revision in pnacl/DEPS
> r11108: (mseaborn) Signal handling: Remove the handler list which never contained >2 entries
> r11109: (olonho) Allow passing raw code on command line of validator.
> r11110: (jfb) Improve toolchain download error message.
> r11111: (mseaborn) PNaCl: Update LLVM revision in pnacl/DEPS
> r11112: (ncbray) Provide metadata to validator to allow faster caching.
> r11113: (mseaborn) PNaCl: Update performance expectations for recent toolchain changes
> r11114: (shcherbina) Validator_ragel: delete gen_dfa.cc.
> r11115: (shcherbina) Validator_ragel: sort switch clauses in code generator.
> r11116: (shcherbina) Validator_ragel: remove TODOs that are either already done or became irrelevant.
> r11117: (shcherbina) Validator_ragel: remove dfa_compare.py.
> r11118: (shcherbina) Validator_ragel: add some documentation for gen_dfa.
> 
> BUG=none
> TEST=nacl_integration
> 
> Review URL: https://codereview.chromium.org/13474003

TBR=mseaborn@chromium.org
Review URL: https://codereview.chromium.org/13639004

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@192398 0039d316-1c4b-4281-b951-d872f2087c98