Revert 182754 > Fixed browser crash when Telemetry uses Debug build. > > Factored out chrome.benchmarking methods which don't depend on stats table. > > > BUG=168640 > > TEST=tools/telemetry/run_tests --browser=debug PageRunnerTests > > Review URL: https://chromiumcodereview.appspot.com/11801024
Win7 perf bot throws error:
AttributeError: 'module' object has no attribute 'check_output

TBR=danhn@chromium.org
Review URL: https://codereview.chromium.org/12277013

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@182824 0039d316-1c4b-4281-b951-d872f2087c98