Revert r150249 "Rolling GYP to r1452:"
It broke Win Builder 2008:

7>------ Build started: Project: chrome_tab_idl, Configuration: Debug Win32 ------
7>Creating Type Library...
7>midl : command line warning MIDL1009 : unknown argument ignored ".\chrome_tab.idl"
7>GrGLConfig_chrome.h""
7>Processing GrGLConfig_chrome.h\""
7>c1 : fatalerror C1083: Cannot open source file: 'GrGLConfig_chrome.h""': Invalid argument
7>midl : command line error MIDL1003 : error returned by the C preprocessor (2)

BUG=chromium:140324
TBR=alexeypa@chromium.org

Review URL: https://chromiumcodereview.appspot.com/10829216

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@150317 0039d316-1c4b-4281-b951-d872f2087c98